// BlueprintGeneratedClass TBFL_UI_Text.TBFL_UI_Text_C
// Size: 0x28 (Inherited: 0x28)
struct UTBFL_UI_Text_C : UBlueprintFunctionLibrary {

	void SetTextCapitalized(struct URichTextBlock* InTextBlock, struct FText InText, struct UObject* __WorldContext); // Function TBFL_UI_Text.TBFL_UI_Text_C.SetTextCapitalized // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x16c0340
	void Get Timespan As UI Text For Store Entries(struct FTimespan InTimeStamp, struct UObject* __WorldContext, struct FText Text); // Function TBFL_UI_Text.TBFL_UI_Text_C.Get Timespan As UI Text For Store Entries // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x16c0340
	void GetMidasResponseText(enum class EShMidasResultCode InMidasResult, struct UObject* __WorldContext, struct FText Text); // Function TBFL_UI_Text.TBFL_UI_Text_C.GetMidasResponseText // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x16c0340
	void GetBuyResponseText(enum class ETigerBuyStoreEntryResponseCode InResponse, struct UObject* __WorldContext, struct FText Text); // Function TBFL_UI_Text.TBFL_UI_Text_C.GetBuyResponseText // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x16c0340
	void GetSeasonExperienceSourceUIText(enum class ETigerSeasonExperienceSource InExperieceSource, int32_t InMatchPlacement, struct UObject* __WorldContext, struct FText OutText); // Function TBFL_UI_Text.TBFL_UI_Text_C.GetSeasonExperienceSourceUIText // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x16c0340
	void Int To Digital Time Text(int32_t InValue, struct UObject* __WorldContext, struct FText AsDigitalTime); // Function TBFL_UI_Text.TBFL_UI_Text_C.Int To Digital Time Text // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x16c0340
	void Get Timespan As UI Text(struct FTimespan InTimespan, struct UObject* __WorldContext, struct FText Formatted Timespan); // Function TBFL_UI_Text.TBFL_UI_Text_C.Get Timespan As UI Text // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x16c0340
	void Get Discipline Slot From Challenge Requirement(struct FTigerChallengeRequirementDisciplineSlot InChallengeRequirement, struct UObject* __WorldContext, struct FText Highlighted Text); // Function TBFL_UI_Text.TBFL_UI_Text_C.Get Discipline Slot From Challenge Requirement // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x16c0340
	void Get Balance Mode From Challenge Requirement(struct FTigerChallengeRequirementGameMode Mode Requirement, struct UObject* __WorldContext, struct FText Game Mode); // Function TBFL_UI_Text.TBFL_UI_Text_C.Get Balance Mode From Challenge Requirement // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x16c0340
	void Get Clan Name from Challenge Requirement(struct FTigerChallengeRequirementClan Clan Requirement, struct UObject* __WorldContext, struct FText Text); // Function TBFL_UI_Text.TBFL_UI_Text_C.Get Clan Name from Challenge Requirement // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x16c0340
	void Get Weapon Name From Challenge Requirement(struct FTigerChallengeRequirementWeaponType ChallengeRequirement, struct UObject* __WorldContext, struct FText Weapon Name); // Function TBFL_UI_Text.TBFL_UI_Text_C.Get Weapon Name From Challenge Requirement // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x16c0340
	void GetBalanceModeAsUIText(enum class EMatchBalanceMode InBalanceMode, struct UObject* __WorldContext, struct FText Text); // Function TBFL_UI_Text.TBFL_UI_Text_C.GetBalanceModeAsUIText // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x16c0340
	void GetGroupModeAsUIText(enum class ETigerGroupingMode GameGroupMode, struct UObject* __WorldContext, struct FText GroupModeAsText); // Function TBFL_UI_Text.TBFL_UI_Text_C.GetGroupModeAsUIText // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x16c0340
	void GetClanNameAsUIText(enum class ETigerClan InClanEnum, struct UObject* __WorldContext, struct FText ClanName); // Function TBFL_UI_Text.TBFL_UI_Text_C.GetClanNameAsUIText // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x16c0340
	void Get Challenge Target Value(struct UTigerChallenge* TigerChallenge, struct UObject* __WorldContext, struct FText FormattedText); // Function TBFL_UI_Text.TBFL_UI_Text_C.Get Challenge Target Value // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x16c0340
	void GetBloodPotencyInUIText(enum class ETigerBloodPotency BloodPotency, struct UObject* __WorldContext, struct FText BloodPotencyAsText); // Function TBFL_UI_Text.TBFL_UI_Text_C.GetBloodPotencyInUIText // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x16c0340
	void GetNpcTypeInUIText(enum class ETigerNPCType NPCType, struct UObject* __WorldContext, struct FText NPCTypeAsText); // Function TBFL_UI_Text.TBFL_UI_Text_C.GetNpcTypeInUIText // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x16c0340
	void Wrap Text in Markup(struct FName StyleName, struct FText TextToFormat, struct UObject* __WorldContext, struct FText FormattedText); // Function TBFL_UI_Text.TBFL_UI_Text_C.Wrap Text in Markup // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x16c0340
};

