// BlueprintGeneratedClass TBP_RangedWeapon_Master.TBP_RangedWeapon_Master_C
// Size: 0x201 (Inherited: 0x1e8)
struct UTBP_RangedWeapon_Master_C : UTigerRangedWeapon {
	struct UTigerCameraPreset* CrouchingAimingCameraPreset; // 0x1e8(0x08)
	struct FVector SpreadOfCurrentShot; // 0x1f0(0x0c)
	float Slowed Time; // 0x1fc(0x04)
	enum class ENUM_RangedWeaponCategories AnimRangedWeaponCategory; // 0x200(0x01)

	void GetRangedWeaponCategory(enum class ENUM_RangedWeaponCategories RangedWeaponCategory); // Function TBP_RangedWeapon_Master.TBP_RangedWeapon_Master_C.GetRangedWeaponCategory // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x16c0340
	struct FVector StandardSpread 16(struct UTigerRangedWeaponComponent* RangedWeaponComponent, int32_t BulletIndex, struct FVector In Dir, struct FTigerRangedRandomState RandomState); // Function TBP_RangedWeapon_Master.TBP_RangedWeapon_Master_C.StandardSpread 16 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x16c0340
	struct FVector Horizontal Line(struct UTigerRangedWeaponComponent* RangedWeaponComponent, int32_t BulletIndex, struct FVector In Dir, struct FTigerRangedRandomState RandomState); // Function TBP_RangedWeapon_Master.TBP_RangedWeapon_Master_C.Horizontal Line // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x16c0340
	struct FVector Tri(struct UTigerRangedWeaponComponent* RangedWeaponComponent, int32_t BulletIndex, struct FVector In Dir, struct FTigerRangedRandomState RandomState); // Function TBP_RangedWeapon_Master.TBP_RangedWeapon_Master_C.Tri // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x16c0340
	void OnHitAuthority(struct ATigerCharacter* Instigator, struct ATigerCharacter* Target); // Function TBP_RangedWeapon_Master.TBP_RangedWeapon_Master_C.OnHitAuthority // (Event|Public|BlueprintCallable|BlueprintEvent|Const) // @ game+0x16c0340
	struct FVector Vertical Line(struct UTigerRangedWeaponComponent* RangedWeaponComponent, int32_t BulletIndex, struct FVector In Dir, struct FTigerRangedRandomState RandomState); // Function TBP_RangedWeapon_Master.TBP_RangedWeapon_Master_C.Vertical Line // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x16c0340
	struct FVector StandardSpread 8(struct UTigerRangedWeaponComponent* RangedWeaponComponent, int32_t BulletIndex, struct FVector In Dir, struct FTigerRangedRandomState RandomState); // Function TBP_RangedWeapon_Master.TBP_RangedWeapon_Master_C.StandardSpread 8 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x16c0340
	struct FVector StandardSpread 12(struct UTigerRangedWeaponComponent* RangedWeaponComponent, int32_t BulletIndex, struct FVector In Dir, struct FTigerRangedRandomState RandomState); // Function TBP_RangedWeapon_Master.TBP_RangedWeapon_Master_C.StandardSpread 12 // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x16c0340
	struct FVector NeoArmstrongCycloneJetArmstrongCannon(struct UTigerRangedWeaponComponent* RangedWeaponComponent, int32_t BulletIndex, struct FVector In Dir, struct FTigerRangedRandomState RandomState); // Function TBP_RangedWeapon_Master.TBP_RangedWeapon_Master_C.NeoArmstrongCycloneJetArmstrongCannon // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x16c0340
	struct FVector ProjectileDirectionList(struct UTigerRangedWeaponComponent* RangedWeaponComponent, int32_t BulletIndex, struct FVector In Dir, struct FTigerRangedRandomState RandomState); // Function TBP_RangedWeapon_Master.TBP_RangedWeapon_Master_C.ProjectileDirectionList // (Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x16c0340
	struct FVector DefaultShotgunSpread(struct UTigerRangedWeaponComponent* RangedWeaponComponent, int32_t BulletIndex, struct FVector In Dir, struct FTigerRangedRandomState RandomState); // Function TBP_RangedWeapon_Master.TBP_RangedWeapon_Master_C.DefaultShotgunSpread // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x16c0340
	struct FVector RowBasedGrid(struct UTigerRangedWeaponComponent* RangedWeaponComponent, int32_t BulletIndex, struct FVector In Dir, bool ShouldBeInsideSpreadRadius, int32_t Rows); // Function TBP_RangedWeapon_Master.TBP_RangedWeapon_Master_C.RowBasedGrid // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x16c0340
	struct FVector SmileyFace :D(struct UTigerRangedWeaponComponent* RangedWeaponComponent, int32_t BulletIndex, struct FVector In Dir); // Function TBP_RangedWeapon_Master.TBP_RangedWeapon_Master_C.SmileyFace :D // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x16c0340
	struct FVector CircularSpread(struct UTigerRangedWeaponComponent* RangedWeaponComponent, int32_t BulletIndex, struct FVector In Dir); // Function TBP_RangedWeapon_Master.TBP_RangedWeapon_Master_C.CircularSpread // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x16c0340
	struct FVector TrueShotgunSpread(struct UTigerRangedWeaponComponent* RangedWeaponComponent, int32_t BulletIndex, struct FVector In Dir, struct FTigerRangedRandomState RandomState); // Function TBP_RangedWeapon_Master.TBP_RangedWeapon_Master_C.TrueShotgunSpread // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x16c0340
	struct FVector Triangle(struct UTigerRangedWeaponComponent* RangedWeaponComponent, int32_t BulletIndex, struct FVector In Dir); // Function TBP_RangedWeapon_Master.TBP_RangedWeapon_Master_C.Triangle // (Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x16c0340
};

